export const GET_CITY_WEATHER = "GET_CITY_WEATHER";
export const UPDATE_CITY_WEATHER = "UPDATE_CITY_WEATHER";
export const DELETE_CITY_WEATHER = "DELETE_CITY_WEATHER";
export const FETCH_SAVED_CITIES_DATA = "FETCH_SAVED_CITIES_DATA";
export const ADD_SAVED_CITIES = "ADD_SAVED_CITIES";
